# Generated by Django 4.2.5 on 2023-11-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
