# Generated by Django 4.2.5 on 2023-12-16 11:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
