# Generated by Django 4.2.5 on 2023-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TinyMceApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=1000, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "get_latest_by": "-createdAt",
            },
        ),
    ]
